import NavBar from "./components/NavBar";
import "./globals.css";
import { Montserrat, Unica_One } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600"],
});

const unica = Unica_One({
  subsets: ["latin"],
  variable: "--font-unica",
  weight: ["400"],
});

export const metadata = {
  title: "GetLinked",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${unica.variable}bg-indigo flex max-w-7xl mx-auto flex-col 
      `}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
